use {
    smash::{
        lua2cpp::*,
        phx::*,
        app::{sv_animcmd::*, lua_bind::*, *},
        lib::{lua_const::*, L2CValue, L2CAgent},
        hash40
    },
    smash_script::*,
    smashline::{*, Priority::*}
};

/*
    jab1        ef_test_1
    ftilt       ef_test_2
    up tilt     ef_test_3
    down tilt   ef_test_4
    nair        ef_test_5
    fair        ef_test_6
    bair        ef_test_7
    uair        ef_test_8
    dair        ef_test_9
    side taunt  ef_test_10
    up taunt    ef_test_11
    down taunt  ef_test_12
*/

unsafe extern "C" fn effect_attack11(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_1"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attacks3(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_2"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attackhi3(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_3"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attacklw3(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_4"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attackairn(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_5"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attackairf(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_6"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attackairb(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_7"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attackairhi(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_8"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_attackairlw(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_9"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_appeals(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_10"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_appealhi(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_11"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

unsafe extern "C" fn effect_appeallw(agent: &mut L2CAgentBase) {
    if macros::is_excute(agent) {
        let half_height = WorkModule::get_param_float(agent.module_accessor, hash40("height"), 0) / 2.0;
        macros::EFFECT(agent, Hash40::new("ef_test_12"), Hash40::new("top"), 0, half_height, half_height * 2.0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, true);
    }
}

pub fn install() {
    Agent::new("bayonetta").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("brave").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("buddy").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("captain").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("chrom").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("cloud").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("daisy").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("dedede").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("demon").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("diddy").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("dolly").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("donkey").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("duckhunt").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("edge").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("eflame").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("elight").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("falco").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("fox").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("gamewatch").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("ganon").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("gaogaen").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("gekkouga").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("ike").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("inkling").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("jack").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("kamui").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("ken").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("koopa").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("koopajr").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("krool").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("link").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("littlemac").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("lucario").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("lucas").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("lucina").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("luigi").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("mario").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("mariod").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("marth").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("master").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("metaknight").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("mewtwo").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("miifighter").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("miigunner").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("miiswordsman").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("nana").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("ness").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("packun").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("pacman").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("palutena").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("peach").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("pfushigisou").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("pichu").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("pikachu").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("pit").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("pitb").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("plizardon").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("popo").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("purin").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("pzenigame").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("reflet").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("richter").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("ridley").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("robot").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("rockman").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("rosetta").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("roy").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("ryu").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("samus").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("samusd").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("sheik").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("shulk").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("simon").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("snake").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("sonic").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("szerosuit").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("tantan").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("toonlink").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("trail").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("trail_fire").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("wario").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("wiifit").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("wolf").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("yoshi").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("younglink").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
    Agent::new("zelda").effect_acmd("effect_attack11", effect_attack11, Default).effect_acmd("effect_attacks3", effect_attacks3, Default).effect_acmd("effect_attacks3s", effect_attacks3, Default).effect_acmd("effect_attacks3hi", effect_attacks3, Default).effect_acmd("effect_attacks3lw", effect_attacks3, Default).effect_acmd("effect_attackhi3", effect_attackhi3, Default).effect_acmd("effect_attacklw3", effect_attacklw3, Default).effect_acmd("effect_attackairn", effect_attackairn, Default).effect_acmd("effect_attackairf", effect_attackairf, Default).effect_acmd("effect_attackairb", effect_attackairb, Default).effect_acmd("effect_attackairhi", effect_attackairhi, Default).effect_acmd("effect_attackairlw", effect_attackairlw, Default).effect_acmd("effect_appealsl", effect_appeals, Default).effect_acmd("effect_appealsr", effect_appeals, Default).effect_acmd("effect_appealhil", effect_appealhi, Default).effect_acmd("effect_appealhir", effect_appealhi, Default).effect_acmd("effect_appeallwl", effect_appeallw, Default).effect_acmd("effect_appeallwr", effect_appeallw, Default).install();
}